# Generated by Django 4.2 on 2026-04-06 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('moisture', models.IntegerField(default=0)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WateringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watered_at', models.DateTimeField(auto_now_add=True)),
                ('moisture_before', models.IntegerField()),
                ('moisture_after', models.IntegerField(default=80)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_history', to='plants_api.plant')),
            ],
            options={
                'verbose_name_plural': 'Watering Histories',
                'ordering': ['-watered_at'],
            },
        ),
        migrations.CreateModel(
            name='CareRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_frequency', models.CharField(default='Every 7 days', max_length=100)),
                ('light_requirement', models.CharField(default='Bright indirect light', max_length=100)),
                ('temperature', models.CharField(default='65-75°F', max_length=100)),
                ('humidity', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_requirements', to='plants_api.plant')),
            ],
            options={
                'verbose_name_plural': 'Care Requirements',
            },
        ),
    ]
