# Generated by Django 4.2 on 2026-04-06 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('light_level', models.CharField(default='Moderate', max_length=100)),
                ('humidity', models.CharField(default='Moderate', max_length=100)),
                ('temperature', models.IntegerField(default=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('watering_frequency', models.CharField(default='Weekly', max_length=100)),
                ('light_requirement', models.CharField(default='Moderate', max_length=100)),
                ('temp_range', models.CharField(default='18-24°C', max_length=100)),
                ('humidity', models.CharField(default='Moderate', max_length=100)),
                ('soil_type', models.CharField(default='Well-draining', max_length=100)),
                ('common_issues', models.TextField(blank=True)),
                ('care_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_threshold', models.IntegerField(default=30)),
                ('warning_threshold', models.IntegerField(default=50)),
                ('healthy_threshold', models.IntegerField(default=70)),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('immediately', 'Immediately')], default='daily', max_length=50)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_system_alerts', models.BooleanField(default=True)),
                ('auto_archive_dead_plants', models.BooleanField(default=False)),
                ('dead_plant_threshold', models.IntegerField(default=10)),
                ('data_retention_days', models.IntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='WateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('every-2-days', 'Every 2 Days'), ('every-3-days', 'Every 3 Days'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=50)),
                ('water_amount', models.IntegerField(default=50)),
                ('optimal_time_of_day', models.TimeField(default='06:00')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='plants_api.planttype')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('moisture', 'Moisture Level'), ('time', 'Time-based'), ('weather', 'Weather-based')], max_length=50)),
                ('trigger_value', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('send_alert', 'Send Alert'), ('trigger_watering', 'Trigger Watering'), ('send_notification', 'Send Notification')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
