# Generated by Django 4.2 on 2026-04-12 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants_api', '0002_location_planttype_systemsettings_wateringschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_user', 'Create User'), ('update_user', 'Update User'), ('delete_user', 'Delete User'), ('reset_password', 'Reset Password'), ('change_role', 'Change Role')], max_length=50)),
                ('target_user_id', models.IntegerField()),
                ('target_username', models.CharField(max_length=150)),
                ('target_user_email', models.CharField(blank=True, max_length=254, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['target_user_id', '-timestamp'], name='plants_api__target__ede604_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['admin_user', '-timestamp'], name='plants_api__admin_u_3645d8_idx'),
        ),
    ]
